FROM debian AS build

RUN apt update && apt install -y clang make

WORKDIR /

COPY Makefile .
COPY src src

RUN mkdir target
RUN make target/full-search target/full-search-plan

RUN target/full-search-plan 1 > plan.txt
